### ISSUE TITLE
add_record is failing

### ISSUE THREAD

**Issue by nbommu1** [iamseth/akcli#4]
when I try to add a record to a zone file , it is failing and gives me this message

command ;

akcli.py dns add_record example.com test1 CNAME  test2

No handlers could be found for logger "__main__"
"Failed to add record."

**Comment by nbommu1** [comment]
actually logging issue on my side, here is the actual error:

  zone['zone'][record_type].append({'name': name, 'target': target, 'ttl': ttl, 'active': True})
KeyError: 'zone'

**Comment by iamseth** [comment]
I'm not sure what's happening but I fixed logging to get some more info. If you update to the latest version 0.1.3 and re-run the command, it may provide more helpful information.

You can upgrade with the following command.

```bash
sudo pip install -U akcli
```

**Comment by nbommu1** [comment]
thanks a lot.

**Comment by iamseth** [comment]
I haven't heard back so I'm assuming I can close this. Re-open if you still need help.
